version: "2"
services:
  admanager:
    container_name: adm
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
    volumes:
      - .:/home/nodejs/app
      - /home/nodejs/app/node_modules 
    environment:
      - MONGO_URI=mongodb://mongo:27017/AdManagerDB
      - PORT=3000
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - /var/microservices/mongo/data:/data/db
    ports:
      - "27018:27017"
